// Invoice With Proof Gallery Template
// Reuses the default template for invoice pages, then appends campaign proof gallery pages

import jsPDF from 'jspdf';
import { InvoiceData, formatDate, COMPANY_ADDRESS } from './types';
import { renderDefaultTemplate } from './defaultTemplate';
import { getCampaignAssetProofPhotos } from '@/lib/exports/proofPhotos';
import { fetchImageAsDataUri } from '@/lib/exports/imageData';
import { supabase } from '@/integrations/supabase/client';
import { getSignedUrl } from '@/utils/storage';

interface ProofAssetBlock {
  assetCode: string | null;
  location: string;
  area: string;
  mediaType: string;
  dimensions: string;
  direction: string;
  period: string;
  photos: { label: string; dataUri: string }[];
}

async function resolveImageUrl(url: string): Promise<string | null> {
  if (!url) return null;
  if (url.startsWith('data:')) return url;
  if (url.startsWith('http')) {
    try { return await fetchImageAsDataUri(url); } catch { return null; }
  }
  // Supabase storage path
  try {
    const parts = url.split('/');
    const bucket = parts[0] || 'operations-photos';
    const path = parts.slice(1).join('/');
    const signed = await getSignedUrl(bucket, path);
    if (!signed) return null;
    return await fetchImageAsDataUri(signed);
  } catch { return null; }
}

/**
 * Render invoice with proof gallery.
 * If data has proofAssets populated, appends gallery pages after the invoice.
 */
export async function renderInvoiceWithProofTemplate(data: InvoiceData): Promise<Blob> {
  // Step 1: Generate the normal invoice PDF using default template
  const invoiceBlob = await renderDefaultTemplate(data);

  // Step 2: Check if proof gallery should be appended
  const proofAssets: ProofAssetBlock[] = (data as any).__proofGalleryAssets || [];
  if (proofAssets.length === 0) {
    return invoiceBlob; // No proof data - return invoice as-is
  }

  // Step 3: Load the invoice PDF into a new jsPDF doc to append pages
  const invoiceArrayBuffer = await invoiceBlob.arrayBuffer();
  const invoiceUint8 = new Uint8Array(invoiceArrayBuffer);

  // We need to create a fresh doc and append proof gallery pages
  // Since jsPDF can't easily merge, we'll re-render invoice + gallery together
  // by loading the existing PDF and adding pages to it
  
  // Use jsPDF's ability to load existing PDF (not supported natively)
  // Instead, we'll create gallery as a separate section appended via a shared jsPDF instance
  // The cleanest approach: render default template returns a Blob, we create gallery pages separately,
  // then merge using a simple PDF merger approach
  
  // For simplicity and reliability, we'll create the gallery as additional pages
  // using a new jsPDF doc and merge the two
  const { default: jsPDFLib } = await import('jspdf');
  
  const galleryDoc = new jsPDFLib({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = galleryDoc.internal.pageSize.getWidth();
  const pageHeight = galleryDoc.internal.pageSize.getHeight();
  const leftMargin = 12;
  const rightMargin = 12;
  const contentWidth = pageWidth - leftMargin - rightMargin;
  const companyName = data.company?.name || data.orgSettings?.organization_name || 'Matrix Network Solutions';

  let isFirstPage = true;

  const addGalleryHeader = (doc: jsPDF, yStart: number): number => {
    let y = yStart;

    // Title banner
    doc.setFillColor(30, 64, 175); // Deep blue
    doc.rect(leftMargin, y, contentWidth, 10, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('CAMPAIGN PROOF GALLERY', pageWidth / 2, y + 7, { align: 'center' });
    y += 14;

    // Reference info
    doc.setTextColor(60, 60, 60);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');

    const invoiceId = data.invoice?.id || '-';
    const campaignName = data.campaign?.name || data.campaign?.campaign_name || '-';
    const clientName = data.client?.name || '-';
    const period = data.campaign
      ? `${formatDate(data.campaign.start_date)} to ${formatDate(data.campaign.end_date)}`
      : '-';

    const refLines = [
      `Invoice: ${invoiceId}`,
      `Campaign: ${campaignName}`,
      `Client: ${clientName}`,
      `Period: ${period}`,
    ];

    refLines.forEach(line => {
      doc.text(line, leftMargin, y);
      y += 4;
    });

    y += 2;
    // Separator line
    doc.setDrawColor(200, 200, 200);
    doc.setLineWidth(0.3);
    doc.line(leftMargin, y, pageWidth - rightMargin, y);
    y += 4;

    return y;
  };

  const addFooter = (doc: jsPDF) => {
    const footerY = pageHeight - 8;
    doc.setFontSize(6.5);
    doc.setTextColor(140, 140, 140);
    doc.setFont('helvetica', 'normal');
    doc.text(`Generated by ${companyName}`, pageWidth / 2, footerY, { align: 'center' });
    doc.text(
      `Page ${doc.internal.pages.length - 1}`,
      pageWidth - rightMargin,
      footerY,
      { align: 'right' }
    );
  };

  let yPos = 14;

  // Render each asset block
  for (let i = 0; i < proofAssets.length; i++) {
    const asset = proofAssets[i];

    // Check if we need a new page
    const requiredHeight = 80; // Estimated min height for an asset block
    if (!isFirstPage && yPos + requiredHeight > pageHeight - 15) {
      addFooter(galleryDoc);
      galleryDoc.addPage();
      yPos = 14;
      yPos = addGalleryHeader(galleryDoc, yPos);
    }

    if (isFirstPage) {
      yPos = addGalleryHeader(galleryDoc, yPos);
      isFirstPage = false;
    }

    // Asset info block
    doc_setAssetHeader(galleryDoc, asset, yPos, leftMargin, contentWidth);
    yPos += 14;

    // Photos grid
    if (asset.photos.length === 0) {
      galleryDoc.setFontSize(8);
      galleryDoc.setTextColor(160, 160, 160);
      galleryDoc.setFont('helvetica', 'italic');
      galleryDoc.text('Proof Pending', leftMargin + 4, yPos + 4);
      yPos += 10;
    } else {
      const photoCount = Math.min(asset.photos.length, 4);
      const cols = photoCount <= 2 ? 2 : 2;
      const rows = Math.ceil(photoCount / cols);
      const imgWidth = (contentWidth - 4) / cols;
      const imgHeight = 45;

      for (let r = 0; r < rows; r++) {
        // Check page break for photo rows
        if (yPos + imgHeight + 10 > pageHeight - 15) {
          addFooter(galleryDoc);
          galleryDoc.addPage();
          yPos = 14;
          yPos = addGalleryHeader(galleryDoc, yPos);
        }

        for (let c = 0; c < cols; c++) {
          const idx = r * cols + c;
          if (idx >= photoCount) break;

          const photo = asset.photos[idx];
          const xPos = leftMargin + c * (imgWidth + 2);

          // Photo border
          galleryDoc.setDrawColor(220, 220, 220);
          galleryDoc.setLineWidth(0.3);
          galleryDoc.rect(xPos, yPos, imgWidth, imgHeight);

          try {
            galleryDoc.addImage(photo.dataUri, 'JPEG', xPos + 0.5, yPos + 0.5, imgWidth - 1, imgHeight - 5);
          } catch {
            galleryDoc.setFontSize(7);
            galleryDoc.setTextColor(180, 180, 180);
            galleryDoc.text('Image unavailable', xPos + imgWidth / 2, yPos + imgHeight / 2, { align: 'center' });
          }

          // Photo label
          galleryDoc.setFontSize(6);
          galleryDoc.setTextColor(100, 100, 100);
          galleryDoc.setFont('helvetica', 'normal');
          galleryDoc.text(photo.label, xPos + imgWidth / 2, yPos + imgHeight - 1, { align: 'center' });
        }
        yPos += imgHeight + 3;
      }
    }

    yPos += 4;

    // Separator between assets
    if (i < proofAssets.length - 1) {
      galleryDoc.setDrawColor(230, 230, 230);
      galleryDoc.setLineWidth(0.2);
      galleryDoc.line(leftMargin + 10, yPos, pageWidth - rightMargin - 10, yPos);
      yPos += 4;
    }
  }

  addFooter(galleryDoc);

  // Now merge: invoice PDF + gallery PDF
  // Since jsPDF can't merge existing PDFs natively on the client,
  // we'll use pdf-lib-like approach or simply use the gallery blob
  // The most reliable approach: use the invoice blob + gallery blob merged via a simple combiner
  
  // Use a lightweight merge approach with arraybuffers
  const galleryBlob = galleryDoc.output('blob');

  // Merge using PDF structure manipulation
  const mergedBlob = await mergePDFs(invoiceBlob, galleryBlob);
  return mergedBlob;
}

function doc_setAssetHeader(doc: jsPDF, asset: ProofAssetBlock, y: number, leftMargin: number, contentWidth: number) {
  // Asset info background
  doc.setFillColor(245, 247, 250);
  doc.rect(leftMargin, y, contentWidth, 12, 'F');
  doc.setDrawColor(200, 200, 210);
  doc.setLineWidth(0.2);
  doc.rect(leftMargin, y, contentWidth, 12, 'S');

  // Asset code / location
  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(30, 30, 30);
  const title = asset.assetCode
    ? `${asset.assetCode} - ${asset.location}`
    : asset.location;
  doc.text(title, leftMargin + 3, y + 4.5);

  // Details line
  doc.setFontSize(6.5);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(80, 80, 80);
  const details = [asset.area, asset.mediaType, asset.dimensions, asset.direction]
    .filter(Boolean)
    .join(' | ');
  doc.text(details, leftMargin + 3, y + 8.5);

  // Period on right
  doc.setFontSize(6.5);
  doc.setTextColor(100, 100, 100);
  doc.text(asset.period, leftMargin + contentWidth - 3, y + 4.5, { align: 'right' });
}

/**
 * Merge two PDF blobs into one using pdf-lib-like approach.
 * Falls back to returning just the first blob if merge fails.
 */
async function mergePDFs(blob1: Blob, blob2: Blob): Promise<Blob> {
  try {
    // Dynamic import of pdf-lib for merging
    const { PDFDocument } = await import('pdf-lib');
    
    const [buf1, buf2] = await Promise.all([
      blob1.arrayBuffer(),
      blob2.arrayBuffer(),
    ]);

    const mergedPdf = await PDFDocument.create();
    
    const pdf1 = await PDFDocument.load(buf1);
    const pdf2 = await PDFDocument.load(buf2);

    const pages1 = await mergedPdf.copyPages(pdf1, pdf1.getPageIndices());
    pages1.forEach(p => mergedPdf.addPage(p));

    const pages2 = await mergedPdf.copyPages(pdf2, pdf2.getPageIndices());
    pages2.forEach(p => mergedPdf.addPage(p));

    const mergedBytes = await mergedPdf.save();
    return new Blob([mergedBytes.buffer as ArrayBuffer], { type: 'application/pdf' });
  } catch (e) {
    console.error('PDF merge failed, returning invoice only:', e);
    return blob1;
  }
}

/**
 * Fetch proof gallery data for campaign assets.
 * Returns an array of ProofAssetBlock ready for rendering.
 */
export async function fetchProofGalleryData(
  campaignId: string,
  items: any[]
): Promise<ProofAssetBlock[]> {
  if (!campaignId) return [];

  // Fetch campaign assets with photos
  const { data: campAssets } = await supabase
    .from('campaign_assets')
    .select('id, asset_id, location, area, city, media_type, dimensions, direction, photos, booking_start_date, booking_end_date')
    .eq('campaign_id', campaignId)
    .eq('is_removed', false);

  if (!campAssets || campAssets.length === 0) return [];

  // Fetch asset codes
  const assetIds = campAssets.map(ca => ca.asset_id).filter(Boolean);
  const { data: maData } = assetIds.length > 0
    ? await supabase.from('media_assets').select('id, media_asset_code').in('id', assetIds)
    : { data: [] };
  const codeMap = new Map((maData || []).map(m => [m.id, m.media_asset_code]));

  const blocks: ProofAssetBlock[] = [];

  for (const ca of campAssets) {
    const proofEntries = getCampaignAssetProofPhotos(ca.photos);

    // Resolve images to data URIs (in parallel, max 4)
    const photoPromises = proofEntries.slice(0, 4).map(async (entry) => {
      const dataUri = await resolveImageUrl(entry.url);
      if (!dataUri) return null;
      return { label: entry.label, dataUri };
    });

    const resolvedPhotos = (await Promise.all(photoPromises)).filter(Boolean) as { label: string; dataUri: string }[];

    const period = (ca.booking_start_date && ca.booking_end_date)
      ? `${formatDate(ca.booking_start_date)} to ${formatDate(ca.booking_end_date)}`
      : '-';

    blocks.push({
      assetCode: codeMap.get(ca.asset_id) || null,
      location: ca.location || '-',
      area: ca.area || ca.city || '-',
      mediaType: ca.media_type || '-',
      dimensions: ca.dimensions || '-',
      direction: ca.direction || '-',
      period,
      photos: resolvedPhotos,
    });
  }

  return blocks;
}
